### ISSUE TITLE
TransMock locks when an Soap Fault is sent as response

### ISSUE THREAD

**Issue by Anders318** [svetvasilev/transmock#16]
Hi!

I have found a problem when I try to test an orchestration that expoces a WCF service that respondes with a Soap Fault. I can see that BizTalk is getting the request, process it and respondes with the Soap Fault. But the test in Transmock never retruns. I have done some debugging and found that the while loop in the lines 220-232 in the method ReadStream() in StreamingNamedPipeClient.cs (see below) never ends.

```
while (!eofReached)
{
    byteCountRead = this.pipeClient.Read(inBuffer, 0, inBuffer.Length);

    eofReached = NamedPipeMessageUtils.IsEndOfMessage(
        inBuffer.Length, 
        byteCountRead);

    msgStream.Write(
        inBuffer,
        0,
        byteCountRead);
}
```
byteCountRead is always zero and eofReached is false in every itteration of the loop.

A'm I doing somthing wrong, or is this a bug or a known limitation of TransMock?

**Comment by svetvasilev** [comment]
Hi Anders, this sounds more like a bug than a feature :) It is a valid point that i do not have any test involving faults so there might be some surprise there in the sense of some sort of automatic handling of such in the WCF adapter framework. I will try to add such a test and reproduce the issue. Could you please share if you are using the latest version of TransMock for your scenario, thanks?

**Comment by Anders318** [comment]
Hi  Svetoslav, I was not on the latest version of TransMock. But I have now upgraded to the latest verson (1.4) and tested. It now behaves diffrently, the test don't locks up but an exception is throwed indicating the Soap Fault message don't get back to the test, see below. I can also tell you I'm testing this with BizTalk 2010 on Windows 7.
I would very much appreciate if you could make it possible to test when there is an expected Soap Fault coming back from BizTalk.
```
Test method IntegrationTests.TransTest.SoapFaultFromBizTalk threw exception: 
BizUnit.Core.TestBuilder.TestStepExecutionException: BizUnit encountered an error executing a test step ---> System.Runtime.Serialization.SerializationException: Attempting to deserialize an empty stream.
    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at TransMock.Communication.NamedPipes.StreamingNamedPipeClient.ReadMessage()
   at TransMock.Integration.BizUnit.MockSolicitResponseStep.ReceiveResponse(Context context)
   at TransMock.Integration.BizUnit.MockSendStep.Execute(Context context)
   at TransMock.Integration.BizUnit.MockSolicitResponseStep.Execute(Context context)
   at BizUnit.Core.TestRunner.ExecuteXamlTestStep(TestStepBase testStep, TestStage stage)
 --- End of inner exception stack trace ---
    at BizUnit.Core.TestRunner.RunTestInternal(TestCase xamlTestCase)
   at BizUnit.Core.TestRunner.Run()
   at IntegrationTests.TransTest.SoapFaultFromBizTalk()
```

**Comment by svetvasilev** [comment]
Hi Anders, apols for the big delay in my response. Good news is I was finally able to reproduce the issue in a unit test. But i still havent figured a way around it. Did you perhaps have some advancement on the matter at your end?
Cheers, Svet

**Comment by Anders318** [comment]
No, I have not found any solution or workaround to this problem.

**Comment by svetvasilev** [comment]
Hi again, just uploaded a new version (1.4.1) of the mock adapter NuGet package that includes a fix for the issue. Now the behavior is that the inbound handler returns the entire SOAP:Envelope in the case of fault response messages. If a normal message is the response it behaves as before - returns the Body of the message.
Please test when you have time and close the issue if satisfied.
Cheers, Svet

**Comment by svetvasilev** [comment]
Closing the issue as I interpret the lack of response as a consent to the fix working as expected. Re-open if otherwise.

**Comment by ola70** [comment]
Hi,

I have tested the latest version and when Biztalk responds with a fault message the test runs as expected. My problem is when I try to make some validations of values in the fault message. It seems that the response is not interpreted as a valid xml document. In the attached test output below you can see that the response has some extra lines of characters and text in the beginning and end. I would appreciate if you could try this and see if you get the same problem. In BizTalk the message looks correctly.

-------------------------------------------------------------------------------
                                   S T A R T
 
Test: Test_SystemException started @ 13:23:45.555 19-12-2018 by Tester
-------------------------------------------------------------------------------
Info: Adding context property: BizUnitTestCaseStartTime, value: 2018-12-19 13:23:45
 
Setup Stage: started @ 13:23:45.561 19-12-2018
 
Setup Stage: ended @ 13:23:45.563 19-12-2018
 
Execute Stage: started @ 13:23:45.563 19-12-2018
Info: Queuing concurrent step: TransMock.Integration.BizUnit.MockSolicitResponseStep for execution

Step: TransMock.Integration.BizUnit.MockSolicitResponseStep started  c o n c u r r e n t l y  @ 13:23:45.565 19-12-2018, failOnError = True
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Data: Reading request content from path TestData\
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Info: Waiting to read the response from the endpoint
Info: Reading the response from the endpoint
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Data: The response received from the mocked endpoint is:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VsaVD
\0??Xhttp://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher/faultVV?V?V??s?:?ReceiverV?V?	

aRhttp://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher?a?:?InternalServiceFaultV?V?xmllang?sv-SE?
<ns0:FaultEnvelope 

xmlns:ns0="http://schemas.microsoft.biztalk.practices.esb.com/exceptionhandling">
  <Application>Testapp</Application>
  <Description>There is no value associated with the property 'Test' in the message.</Description>
  <ErrorType>MissingPropertyException</ErrorType>
  <FailureCategory>BizTalk.Orchestration</FailureCategory>
  <FaultCode>GeneralException</FaultCode>
  <FaultDescription>Error description not available</FaultDescription>
  <FaultSeverity>2</FaultSeverity>
  <Scope>Construct Fault Message</Scope>
  <ServiceInstanceID>e4c29c2a-1f0a-4bde-91ca-32df28fb7eaa</ServiceInstanceID>
  <ServiceName>Testapp.Orchestrations.Test</ServiceName>
</ns0:FaultEnvelope>V?@ExceptionDetail;http://schemas.datacontract.org/2004/07/System.ServiceModel	i)http://www.w3.org/2001/XMLSchema-

instance@HelpLink.nil?@InnerException.nil?@Message?
<ns0:FaultEnvelope xmlns:ns0="http://schemas.microsoft.biztalk.practices.esb.com/exceptionhandling">
  <Application>Testapp</Application>
  <Description>There is no value associated with the property 'Test' in the message.</Description>
  <ErrorType>MissingPropertyException</ErrorType>
  <FailureCategory>BizTalk.Orchestration</FailureCategory>
  <FaultCode>GeneralException</FaultCode>
  <FaultDescription>Error description not available</FaultDescription>
  <FaultSeverity>2</FaultSeverity>
  <Scope>Construct Fault Message</Scope>
  <ServiceInstanceID>e4c29c2a-1f0a-4bde-91ca-32df28fb7eaa</ServiceInstanceID>
  <ServiceName>Testapp.Orchestrations.GranskaDebitering</ServiceName>
</ns0:FaultEnvelope>@
StackTrace?   at Microsoft.BizTalk.Adapter.Wcf.Runtime.BizTalkAsyncResult.End()
   at Microsoft.BizTalk.Adapter.Wcf.Runtime.BizTalkServiceInstance.EndOperation(IAsyncResult result)
   at Microsoft.BizTalk.Adapter.Wcf.Runtime.BizTalkServiceInstance.Microsoft.BizTalk.Adapter.Wcf.Runtime.ITwoWayAsync.EndTwoWayMethod(IAsyncResult result)
   at AsyncInvokeEndEndTwoWayMethod(Object , Object[] , IAsyncResult )
   at System.ServiceModel.Dispatcher.AsyncMethodInvoker.InvokeEnd(Object instance, Object[]& outputs, IAsyncResult result)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeEnd(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage7(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)@Type?:Microsoft.BizTalk.Adapter.Wcf.Runtime.BizTalkNackException
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*******************************************************************************
Error: Exception caught!
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XsdValidatingReader.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at BizUnit.TestSteps.ValidationSteps.Xml.XmlValidationStep.ValidateXmlInstance(Stream data, Context context)
*******************************************************************************
*******************************************************************************
Error: Exception caught!
BizUnit.Core.TestBuilder.ValidationStepExecutionException: Failed to validate document instance ---> System.Xml.XmlException: Data at the root level is invalid. Line 

1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XsdValidatingReader.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at BizUnit.TestSteps.ValidationSteps.Xml.XmlValidationStep.ValidateXmlInstance(Stream data, Context context)
   --- End of inner exception stack trace ---
   at BizUnit.TestSteps.ValidationSteps.Xml.XmlValidationStep.ValidateXmlInstance(Stream data, Context context)
   at BizUnit.TestSteps.ValidationSteps.Xml.XmlValidationStep.Execute(Stream data, Context context)
   at TransMock.Integration.BizUnit.MockSolicitResponseStep.Execute(Context context)
   at BizUnit.Core.Utilites.ConcurrentTestStepWrapper.Execute()
*******************************************************************************

Step: TransMock.Integration.BizUnit.MockSolicitResponseStep ended @ 13:23:46.569 19-12-2018 with ERRORS, exception: 

BizUnit.Core.TestBuilder.ValidationStepExecutionException
*******************************************************************************
Error: Exception caught!
BizUnit.Core.TestBuilder.ValidationStepExecutionException: Failed to validate document instance ---> System.Xml.XmlException: Data at the root level is invalid. Line 

1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XsdValidatingReader.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at BizUnit.TestSteps.ValidationSteps.Xml.XmlValidationStep.ValidateXmlInstance(Stream data, Context context)
   --- End of inner exception stack trace ---
   at BizUnit.Core.TestRunner.FlushConcurrentQueue(Boolean waitingToFinish, TestStage stage)
   at BizUnit.Core.TestRunner.ExecuteSteps(IEnumerable`1 testSteps, TestStage stage)
*******************************************************************************
 
Execution Stage: ended @ 13:23:46.570 19-12-2018 with ERROR's
 
Cleanup Stage: started @ 13:23:46.570 19-12-2018
*******************************************************************************
Error: Exception caught!
BizUnit.Core.TestBuilder.ValidationStepExecutionException: Failed to validate document instance ---> System.Xml.XmlException: Data at the root level is invalid. Line 

1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XsdValidatingReader.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at BizUnit.TestSteps.ValidationSteps.Xml.XmlValidationStep.ValidateXmlInstance(Stream data, Context context)
   --- End of inner exception stack trace ---
   at BizUnit.Core.TestRunner.FlushConcurrentQueue(Boolean waitingToFinish, TestStage stage)
   at BizUnit.Core.TestRunner.ExecuteSteps(IEnumerable`1 testSteps, TestStage stage)
*******************************************************************************
 
Cleanup Stage: ended @ 13:23:46.570 19-12-2018 with ERROR's


Debug Trace:
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: Connect() called
TransMock.Communication.NamedPipe.StreamingNamedPipeServer: Connecting to named pipe server at: localhost//Test_ReceiveAddress
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: WriteStream() called
TransMock.Communication.NamedPipes: WriteStream() succeeded. Message read by the server
TransMock.Communication.NamedPipes: WriteMessage() succeeded. Message read by the server
TransMock.Integration.BizUnit.MockSolicitResponseStep: Reading the response from the endpoint
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: ReadMessage() called
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: ReadStream() called
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: ReadStream() succeeded
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: Deserializing message from the pipe.
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: ReadMessage() succeeded and returning data
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: Disconnect() called
TransMock.Communication.NamedPipes.StreamingNamedPipeClient: Disconnect() succeeded
TransMock.Integration.BizUnit.MockSendStep: PipeClient closed
